version: 2

services:
  api:
    build:
      builder: NIXPACKS
      buildCommand: pnpm install && pnpm turbo build --filter @repo/api
    deploy:
      startCommand: pnpm --filter @repo/api start
      healthcheckPath: /api/health
      healthcheckTimeout: 100
      restartPolicyType: ON_FAILURE
      restartPolicyMaxRetries: 10
      env:
        NODE_ENV: production
  
  web:
    build:
      builder: NIXPACKS
      buildCommand: pnpm install && pnpm turbo build --filter @repo/web
    deploy:
      startCommand: pnpm --filter @repo/web start
      healthcheckPath: /
      restartPolicyType: ON_FAILURE
      env:
        NODE_ENV: production
